language: node_js
node_js:
  - "12"
before_script:
  - yarn
script:
  - yarn build
deploy:
  github_token: $GH_TOKEN
  provider: pages
  skip_cleanup: true
  keep_history: true
  on: 
    branch: master
  local_dir: ./build  